force-app/main/default/objects/Slack_Webhook__c/Slack_Webhook__c.object-meta.xml
<CustomObject>
    <label>Slack Webhook</label>
    <nameField>
        <label>Slack Webhooks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slack Webhooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slack_Webhook__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Indicates if the webhook should be used to send notifications. Disabling will prevent messages being sent to slack</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Slack_Webhook__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <inlineHelpText>The webhook URL from the slack app. Example: https://hooks.slack.com/services/########/##########/#######################</inlineHelpText>
    <label>URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/SlackPostActionTEST.cls
@IsTest
public with sharing class SlackPostActionTEST {

    @IsTest
    static void testPost(){

        Slack_Webhook__c wh = new Slack_Webhook__c();
        wh.Name = 'Test Webhook Name';
        wh.Enabled__c = true;
        wh.URL__c = 'https://hooks.slack.com/services/F08B45ZLF/AZ0PQU4MJ/WuKxVfy3xsD9U67TiQZO8oM5';
        insert wh;

        SlackPostAction.SlackPostRequest spr = new SlackPostAction.SlackPostRequest('Test Text', wh.Name);
        spr.fallback = 'Test Fallback';
        spr.color = '#36a64f';
        spr.pretext = 'Test Pretext';
        spr.author_name = 'Test Author';
        spr.author_link = 'https://test.authorlink.com';
        spr.author_icon = 'https://test.authorlink.com/icon.jpg';
        spr.title = 'Test Title';
        spr.title_link = 'https://test.titlelink.com';
        spr.webhookName = 'Test Webhook Name';
        spr.field1 = '{"title": "TEST FIELD 1","value": "Something Here1\\nSomething Else1","short": false}';
        spr.field3 = '{"title": "TEST FIELD 3","value": "Something Here3\\nSomething Else3","short": false}';

        test.startTest();
            SlackPostAction.sendSlackPost(spr);
        test.stopTest();
    }
}